// Shared API types. Generated by hand from docs/CONTRACT.md.
// Placeholder in this pass; the contract doc is written first.

export type ApiMode = 'mock' | 'live';

export interface ApiError {
  code: string;
  message: string;
}
